CREATE TABLE IF NOT EXISTS language_levels (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    language TEXT NOT NULL,
    question_id INTEGER NOT NULL,
    file_name TEXT NOT NULL,
    full_path TEXT NOT NULL,
    status INTEGER NOT NULL,
    transcribe_text TEXT NULL,
    level TEXT NULL,
    grammatic_exceptions TEXT NULL,
    grammatic_exceptions_score REAL NULL,
    lexical_weaknesses TEXT NULL,
    lexical_weaknesses_score REAL NULL,
    additional_comments TEXT NULL,
    pragmatic_context TEXT NULL,
    pragmatic_context_score REAL NULL,
    stylistic_appropriateness TEXT NULL,
    stylistic_appropriateness_score REAL NULL,
    vocabulary_diversity TEXT NULL,
    vocabulary_diversity_score REAL NULL,
    sentence_complexity TEXT NULL,
    sentence_complexity_score REAL NULL,
    engagement_level TEXT NULL,
    engagement_level_score REAL NULL,
    tone_and_sentiment TEXT NULL,
    tone_and_sentiment_score REAL NULL,
    overall_score REAL NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL
);